# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.04.23
_src_path: gh:scientific-python/cookie
backend: hatch
email: nstarman@users.noreply.github.com
full_name: Nathaniel Starkman
license: MIT
org: GalacticDynamics
project_name: dataclassish
project_short_description: dataclass tools, extended by multiple dispatch
url: https://github.com/GalacticDynamics/dataclassish
vcs: true
